# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: 
        - prometheus.yeungs.net:9090

  - job_name: "node"
    static_configs:
      - targets:
        - proxmox.yeungs.net:9100
        - lab.yeungs.net:9100
        - lab2.yeungs.net:9100

  - job_name: "nvitop-exporter"
    static_configs:
    - targets:
      - lab.yeungs.net:5050

  - job_name: "ipmi_exporter"
    static_configs:
    - targets:
      - lab.yeungs.net:9290

  - job_name: "docker"
    static_configs:
    - targets:
      - lab.yeungs.net:9323

  - job_name: "cadvisor"
    static_configs:
    - targets:
      - lab.yeungs.net:8080

  - job_name: "homeassistant"
    metrics_path: /api/prometheus
    authorization:
      credentials_file: homeassistant_credentials 
    static_configs:
    - targets:
      - homeassistant.yeungs.net:8123

  - job_name: "grafana"
    static_configs:
    - targets:
      - 192.168.50.22:3000

  - job_name: "nvidia_gpu_exporter"
    static_configs:
    - targets:
      - 192.168.50.200:9835

